name: ESP-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout without submodules
        uses: actions/checkout@v4
        with:
          submodules: true # bootstrap script inits submodules inside IDF
          fetch-depth: 1
      
      - name: Cache esp-idf tools
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: ${{ runner.os }}-idf-s3-${{ hashFiles('edge/esp-idf/tools/**') }}
          restore-keys: |
            ${{ runner.os }}-idf-s3-
      
      - name: Init Submodules and Install IDF
        run: . bootstrap-ubuntu.sh

      - name: Build firmware
        run: . esp-idf/export.sh && cd firmware && idf.py set-target esp32s3 build
